# Generated by Django 4.1.5 on 2023-04-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelsMates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate_travelers', to=settings.AUTH_USER_MODEL)),
                ('traveler_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_mates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
