# Generated by Django 4.1.5 on 2023-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='mother_tounge',
            field=models.CharField(default='Telugu', max_length=50),
        ),
    ]
