# Generated by Django 4.1.5 on 2023-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers_app', '0002_traveler_mother_tounge'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='fans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traveler',
            name='mates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traveler',
            name='trips',
            field=models.IntegerField(default=0),
        ),
    ]
