# Generated by Django 4.1.5 on 2023-03-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user_email',
            new_name='traveler',
        ),
    ]
