# Generated by Django 4.1.5 on 2023-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsdata',
            name='image_url',
            field=models.CharField(max_length=800),
        ),
    ]
