# Generated by Django 4.1.5 on 2023-04-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_alter_tripsdata_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripsdata',
            old_name='image_url',
            new_name='image',
        ),
    ]
